### ISSUE TITLE
autos.....

### ISSUE THREAD

**Issue by pcbend** [pcbend/GRUTinizer#4]
auto iter does not work on gcc 4.4.7 (SL 6 and CENTOS 6); This is to large of a user market to ignore, looks like we need to downgrade....

also std=c++11 needs to become std=c++0x for the same reason.

**Comment by pcbend** [comment]
TSmartBufer(TSmartBuffer&&) is also illegal.

**Comment by Lunderberg** [comment]
C++11 support as of g++-4.4: https://gcc.gnu.org/gcc-4.4/cxx0x_status.html

Changes that would need to be made.
- Not using any range-based for loops.
- <atomic> is named <stdatomic.h> in versions prior to gcc 4.6, and so any includes would need to check the gcc version before including them.
- Add -D_GLIBCXX_USE_NANOSLEEP to the compiler flags, since otherwise std::this_thread::sleep_for is unavailable.  Not sure if this introduces other issues.
- The TSmartBuffer(TSmartBuffer&&) move constructor is supported, but the delegating constructor is not.

The range-based for loops and the changes to <atomic> are the big issue, since those are used throughout the code, and are very convenient.

[It looks like](https://access.redhat.com/documentation/en-US/Red_Hat_Developer_Toolset/2/html-single/User_Guide/index.html) RHEL and derivatives (SL and CENTOS) do have the ability to use modern versions of g++, as provided by the devtoolset-2-gcc-c++ package.

CENTOS 7 and SL 7 came out in July and October 2014, so they have been out for a while.  Any idea how quickly adoption is picking up?  I think I'd lean toward keeping the C++11 features in, but adding a check for devtoolset-2-gcc-c++ in the makefile, and using it if present.

**Comment by pcbend** [comment]
this is no longer an issue.
