### ISSUE TITLE
bailing out of a sort early.

### ISSUE THREAD

**Issue by pcbend** [pcbend/GRUTinizer#5]
below are the out statements when bailing out of a file early.  Something we changed recently seems to try and restart the read loop?  This of course causes bad things to happen, it is after the data is written though so it is not a horrible failure. 

File name:  data/Run0133/Global.dat
Read loop starting
Initializing
Status: Write loop starting

   157.38 MB given  /   6431.10 MB total   =>  11.65 MB/s processed              ^C
   Control-c was pressed.  
Error in TApplication::TApplication: only one instance of TApplication allowed
Note: File "DllImport.h" already loaded
Data loop already running
File name:  data/Run0133/Global.dat
terminate called without an active exception
Read loop starting
Aborted

**Comment by Lunderberg** [comment]
I figured out why it is happening.  When the signal handler is called, it makes a call to TGRUTint::instance().  fTGRUTint is not defined at this point, because the TGRUTint constructor has not yet finished.  Therefore, it constructed a second instance of TGRUTint.  The fix was to move the call to TGRUTint::Init into TGRUTint::instance(), rather than being called in the TGRUTint constructor.  This way, fTGRUTint will be non-null by the time that any later calls to TGRUTint::instance() occur.

The fix has been merged into master.
